package pms;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Font;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Rectangle;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.OutputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

public class ViewPatient extends javax.swing.JFrame {
    Connection x = null;
    public ViewPatient() {
        initComponents();
        x = PMSdbConnect.dbConnector();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtIDNO = new javax.swing.JTextField();
        btnViewRecord = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Patient Management System - View a Patient's Records\n");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Patient IDNO :");

        txtIDNO.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnViewRecord.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnViewRecord.setText("View Record");
        btnViewRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewRecordActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pms/PMS logo.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setText("Banda Community Health Centre");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel4.setText("Patients Management System");

        jLabel5.setText("Please type the IDNO for a patient you wish to view and click submit.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnViewRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtIDNO, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIDNO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewRecordActionPerformed
        String IDNO = txtIDNO.getText().toUpperCase();
        String sqlQuery = "select * from pms_store_1 where IDNO=?";// + IDNO + "'";
        
        try {         
            PreparedStatement ps = x.prepareStatement(sqlQuery);
            ps.setString(1, IDNO);
            ResultSet rs = ps.executeQuery();
            
            Font size24 = new Font();
            size24.setSize(24);
            
            if(rs.next()){
                OutputStream file = new FileOutputStream(new File("D:\\PMS RECORDS\\" + IDNO + ".pdf"));
                Document Doc = new Document();
                PdfWriter.getInstance(Doc, file);
                Doc.open();
                
                
                
                PdfPTable imgTable = new PdfPTable(2); // 2 columns
                Image image = Image.getInstance("PMS logo.png");
                PdfPCell img = new PdfPCell(image, true);
                Paragraph BCHC = new Paragraph("   Banda Community Health Centre", size24);
                PdfPCell bchc = new PdfPCell(BCHC);
                Add2cells(Doc, imgTable, img, bchc);
                
                PdfPTable a = new PdfPTable(2);
                a.setSpacingBefore(30f);
                PdfPCell a1 = new PdfPCell(new Paragraph("Patient IDNO :"));
                PdfPCell a2 = new PdfPCell(new Paragraph(rs.getString(1)));
                Add2cells(Doc, a, a1, a2);
                
                PdfPTable b = new PdfPTable(2);
                PdfPCell b1 = new PdfPCell(new Paragraph("Name :"));
                PdfPCell b2 = new PdfPCell(new Paragraph(rs.getString(2)));
                Add2cells(Doc, b, b1, b2);
                
                PdfPTable c = new PdfPTable(2);
                PdfPCell c1 = new PdfPCell(new Paragraph("Age :"));
                PdfPCell c2 = new PdfPCell(new Paragraph(rs.getString(3)));
                Add2cells(Doc, c, c1, c2);
                
                PdfPTable d = new PdfPTable(2);
                PdfPCell d1 = new PdfPCell(new Paragraph("Telephone :"));
                PdfPCell d2 = new PdfPCell(new Paragraph(rs.getString(4)));
                Add2cells(Doc, d, d1, d2);
                
                PdfPTable e = new PdfPTable(2);
                PdfPCell e1 = new PdfPCell(new Paragraph("Email :"));
                PdfPCell e2 = new PdfPCell(new Paragraph(rs.getString(5)));
                Add2cells(Doc, e, e1, e2);
                
                PdfPTable f = new PdfPTable(2);
                f.setSpacingBefore(20f);
                PdfPCell f1 = new PdfPCell(new Paragraph("Diseases :"));
                PdfPCell f2 = new PdfPCell(new Paragraph(rs.getString(6)));
                Add2cells(Doc, f, f1, f2);
                
                PdfPTable g = new PdfPTable(2);
                g.setSpacingBefore(10f);
                PdfPCell g1 = new PdfPCell(new Paragraph("Prescriptions :"));
                PdfPCell g2 = new PdfPCell(new Paragraph(rs.getString(7)));
                Add2cells(Doc, g, g1, g2);
                
                PdfPTable h = new PdfPTable(2);
                h.setSpacingBefore(10f);
                PdfPCell h1 = new PdfPCell(new Paragraph("Bill (UGX) :"));
                PdfPCell h2 = new PdfPCell(new Paragraph(rs.getString(8)));
                Add2cells(Doc, h, h1, h2);
                
                PdfPTable i = new PdfPTable(2);
                PdfPCell i1 = new PdfPCell(new Paragraph("Bill Date :"));
                PdfPCell i2 = new PdfPCell(new Paragraph(rs.getString(9)));
                Add2cells(Doc, i, i1, i2);
                
                Doc.close();
                file.close();

                Runtime.getRuntime().exec("rundll32 url.dll, FileProtocolHandler "
                        + "D:\\PMS RECORDS\\" + IDNO + ".pdf");
                //Display pdf
            }
            else{
                JOptionPane.showMessageDialog(null, "Missing record!");
            }
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnViewRecordActionPerformed

    public void Add2cells(Document x, PdfPTable row, PdfPCell cellA, PdfPCell cellB) throws DocumentException{
        float[] columnWidths = {2f, 8f};
        row.setWidthPercentage(100);
        row.setWidths(columnWidths);
        row.setWidthPercentage(100);
        cellA.setBorder(Rectangle.NO_BORDER);
        cellB.setBorder(Rectangle.NO_BORDER);
        row.addCell(cellA);
        row.addCell(cellB);
        x.add(row);
    }
    
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        dispose();
        Login L =  new Login();
        L.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewPatient().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnViewRecord;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtIDNO;
    // End of variables declaration//GEN-END:variables
}
